# Generated by Django 3.0.2 on 2020-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rollno',
            field=models.IntegerField(),
        ),
    ]
