# Generated by Django 3.0.2 on 2020-03-05 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0002_auto_20200304_1657'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='student',
        ),
    ]
