# Generated by Django 3.0.2 on 2020-03-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0003_auto_20200305_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
