# Generated by Django 3.0.2 on 2020-03-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0004_auto_20200305_1518'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='student',
        ),
    ]
