# Generated by Django 3.0.2 on 2020-03-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formApp', '0005_auto_20200305_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='not available', max_length=150),
        ),
    ]
