# Generated by Django 3.0.2 on 2020-03-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='DateOfBirth',
            field=models.CharField(max_length=20),
        ),
    ]
