# Generated by Django 3.0.2 on 2020-03-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0004_auto_20200309_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='Sex',
            field=models.DateField(),
        ),
    ]
