# Generated by Django 3.0.2 on 2020-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0005_auto_20200309_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='Sex',
            field=models.CharField(max_length=6),
        ),
    ]
