# Generated by Django 3.0.2 on 2020-03-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrApp', '0006_auto_20200309_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='Sex',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='other', max_length=6),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='DateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='MaritalStatus',
            field=models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED')], default='other', max_length=10),
        ),
    ]
